services:
  mysql:
    image: mysql:8.4
    container_name: arena-gamer-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: arena_gamer_db
      MYSQL_USER: arena
      MYSQL_PASSWORD: arena123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # ==========================================
  # SERVICIOS BASE (No dependen de otros MS)
  # ==========================================
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports: ["8081:8081"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql]

  station-service:
    build:
      context: ./station-service
    container_name: station-service
    ports: ["8083:8083"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql]

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports: ["8089:8089"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql]

  loyalty-service:
    build:
      context: ./loyalty-service
    container_name: loyalty-service
    ports: ["8087:8087"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql]

  arena-inventory:
    build:
      context: ./arena-inventory
    container_name: arena-inventory
    ports: ["9001:9001"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql]

  # ==========================================
  # SERVICIOS CON DEPENDENCIAS
  # ==========================================
  arena-wallet:
    build:
      context: ./arena-wallet
    container_name: arena-wallet
    ports: ["8085:8085"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql, user-service]

  arena-reservas:
    build:
      context: ./arena-reservas
    container_name: arena-reservas
    ports: ["9000:9000"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql, arena-inventory]

  session-service:
    build:
      context: ./session-service
    container_name: session-service
    ports: [ "8082:8082" ]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
      - SERVICES_USER_SERVICE_URL=http://user-service:8081
      - SERVICES_STATION_SERVICE_URL=http://station-service:8083
      - SERVICES_WALLET_SERVICE_URL=http://arena-wallet:8085
      - SERVICES_LOYALTY_SERVICE_URL=http://loyalty-service:8087
    depends_on: [ mysql, user-service, station-service, arena-wallet, loyalty-service ]

  hardware-monitor:
    build:
      context: ./hardware-monitor
    container_name: hardware-monitor
    ports: ["8090:8090"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql, notification-service]

  tournament-service:
    build:
      context: ./tournament-service
    container_name: tournament-service
    ports: ["8088:8088"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=arena_gamer_db
      - DB_USER=arena
      - DB_PASSWORD=arena123
    depends_on: [mysql, user-service, notification-service]


  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports: [ "8080:8080" ]
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - STATION_SERVICE_URL=http://station-service:8083
      - SESSION_SERVICE_URL=http://session-service:8082
      - INVENTORY_SERVICE_URL=http://arena-inventory:9001
      - RESERVAS_SERVICE_URL=http://arena-reservas:9000
      - WALLET_SERVICE_URL=http://arena-wallet:8085
      - LOYALTY_SERVICE_URL=http://loyalty-service:8087
      - HARDWARE_SERVICE_URL=http://hardware-monitor:8090
      - NOTIFICATION_SERVICE_URL=http://notification-service:8089
      - TOURNAMENT_SERVICE_URL=http://tournament-service:8088
    depends_on:
      - user-service
      - station-service
      - session-service
      - arena-inventory
      - arena-reservas
      - arena-wallet
      - loyalty-service
      - hardware-monitor
      - notification-service
      - tournament-service

volumes:
  mysql_data:
    
    
