spring:
  application:
    name: station-service
  profiles:
    active: h2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

logging:
  level:
    root: INFO
    com.example.stationservice: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] %logger{0} - %msg%n"
  file:
    name: logs/station-service.log