server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Gateway-Source, arena-gamer-gateway
        - AddResponseHeader=X-Response-Gateway, arena-gamer-platform
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - AddRequestHeader=X-Service-Name, user-service
        - id: station-service
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/stations/**
          filters:
            - AddRequestHeader=X-Service-Name, station-service
        - id: session-service
          uri: lb://SESSION-SERVICE
          predicates:
            - Path=/api/sessions/**
          filters:
            - AddRequestHeader=X-Service-Name, session-service
        - id: arena-inventory
          uri: lb://ARENA-INVENTORY
          predicates:
            - Path=/api/v1/productos/**
          filters:
            - AddRequestHeader=X-Service-Name, arena-inventory
        - id: arena-reservas
          uri: lb://ARENA-RESERVAS
          predicates:
            - Path=/api/v1/reservas/**
          filters:
            - AddRequestHeader=X-Service-Name, arena-reservas
        - id: arena-wallet
          uri: lb://ARENA-WALLET
          predicates:
            - Path=/api/v1/billeteras/**
          filters:
            - AddRequestHeader=X-Service-Name, arena-wallet
        - id: loyalty-service
          uri: lb://LOYALTY-SERVICE
          predicates:
            - Path=/api/v1/loyalty/**
          filters:
            - AddRequestHeader=X-Service-Name, loyalty-service
        - id: hardware-monitor
          uri: lb://HARDWARE-MONITOR
          predicates:
            - Path=/api/v1/hardware/**
          filters:
            - AddRequestHeader=X-Service-Name, hardware-monitor
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AddRequestHeader=X-Service-Name, notification-service
        - id: tournament-service
          uri: lb://TOURNAMENT-SERVICE
          predicates:
            - Path=/api/v1/tournaments/**
          filters:
            - AddRequestHeader=X-Service-Name, tournament-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.cybergamer.apigateway.filter: INFO
